"""
Custom Hatchlink build hook: runs lcm-gen on all .lcm files at the repo root,
generates into a temp directory (zero repo artefacts), and injects the result
into the wheel via force_include.
"""

from __future__ import annotations

import shutil
import subprocess
import tempfile
from pathlib import Path

from hatchling.builders.hooks.plugin.interface import BuildHookInterface

PACKAGE_NAME = "compas_lcmtypes"


class CustomBuildHook(BuildHookInterface):
    PLUGIN_NAME = "custom"

    def initialize(self, version: str, build_data: dict) -> None:
        root = Path(self.root)

        lcm_files = sorted(root.glob("*.lcm"))
        if not lcm_files:
            self.app.display_warning("No .lcm files found at repo root — nothing to generate.")
            return

        self._ensure_lcm_gen()

        # Generate into a temp dir that is cleaned up after the build
        self._tmp = tempfile.mkdtemp(prefix="lcm_gen_")
        gen_root = Path(self._tmp)

        self._run_lcm_gen(lcm_files, gen_root)
        self._write_init(gen_root)

        # Inject every generated file into the wheel at the correct install path.
        # force_include maps  src_path -> wheel-relative destination path.
        pkg_dir = gen_root / PACKAGE_NAME
        for src in pkg_dir.rglob("*.py"):
            rel = src.relative_to(gen_root)          # e.g. compas_lcmtypes/Foo.py
            build_data["force_include"][str(src)] = str(rel)

        self.app.display_info(
            f"Injecting {len(build_data['force_include'])} file(s) "
            f"into wheel as '{PACKAGE_NAME}/'."
        )

    def finalize(self, version: str, build_data: dict, artifact_path: str) -> None:
        tmp = getattr(self, "_tmp", None)
        if tmp:
            shutil.rmtree(tmp, ignore_errors=True)
            self.app.display_info("Cleaned up lcm-gen temp directory.")

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _ensure_lcm_gen(self) -> None:
        if shutil.which("lcm-gen") is None:
            raise RuntimeError(
                "lcm-gen not found on PATH. "
                "Install LCM (https://lcm-proj.github.io/) before building."
            )

    def _run_lcm_gen(self, lcm_files: list[Path], gen_root: Path) -> None:
        pkg_out = gen_root / PACKAGE_NAME
        pkg_out.mkdir(parents=True, exist_ok=True)

        cmd = [
            "lcm-gen",
            "--python",
            f"--ppath={gen_root}",          # lcm-gen writes PACKAGE_NAME/ under here
            f"--package-prefix={PACKAGE_NAME}",    # prefix every generated type
            *[str(f) for f in lcm_files],
        ]

        self.app.display_info(f"Running: {' '.join(cmd)}")
        result = subprocess.run(cmd, capture_output=True, text=True)

        if result.returncode != 0:
            raise RuntimeError(
                f"lcm-gen failed (exit {result.returncode}):\n"
                f"stdout: {result.stdout}\n"
                f"stderr: {result.stderr}"
            )

    def _write_init(self, gen_root: Path) -> None:
        """Write __init__.py that re-exports all generated types."""
        pkg_dir = gen_root / PACKAGE_NAME
        modules = sorted(
            p.stem
            for p in pkg_dir.glob("*.py")
            if p.name != "__init__.py"
        )

        lines = [
            "# Auto-generated by hatch_build.py — do not edit manually.",
            "",
            *[f"from .{m} import *  # noqa: F401, F403" for m in modules],
            "",
        ]
        (pkg_dir / "__init__.py").write_text("\n".join(lines))
        self.app.display_info(f"Generated __init__.py with {len(modules)} module(s).")